
openapi: 3.1.0
info:
  title: MarkTout D2C API
  version: "1.0.0"
servers:
  - url: http://localhost:8000/api/v1
paths:
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: OK
  /auth/register:
    post:
      summary: Register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password]
              properties:
                name: { type: string }
                email: { type: string, format: email }
                password: { type: string, format: password }
      responses:
        "201": { description: Created }
  /auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string, format: email }
                password: { type: string, format: password }
      responses:
        "200": { description: Token }
  /products:
    get:
      summary: List products
      parameters:
        - in: query
          name: q
          schema: { type: string }
        - in: query
          name: category
          schema: { type: string }
        - in: query
          name: sort
          schema:
            type: string
            enum: [price_asc, price_desc, newest]
      responses:
        "200": { description: Paginated products }
  /products/{id}:
    get:
      summary: Get a product
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200": { description: Product }
